import { CentreFacture } from "./CentreFacture";
import { Commune } from "./Commune";
import { MilieuImplantation } from "./MilieuImplantation";
import { Personnel } from "./Personnel";
import { ProprieteDuCentre } from "./ProprieteDuCentre";
import { Province } from "./Province";
import { TypeCentre } from "./TypeCentre";

export type Centre = {
  id?: number;
  nomFr?: string;
  nomAr?: string;
  typeCentre?: TypeCentre;
  dateConstruction?: string;
  telephone?: string;
  province?: Province;
  commune?: Commune;
  adresse?: string;
  responsable?: Personnel;
  milieuImplantation?: MilieuImplantation;
  proprieteDuCentre?: ProprieteDuCentre;
  superficie?: number;
  utilisation?: string;
  etat?: string;
  electricite?: string;
  telephoneFixe?: string;
  internet?: string;
  possession?: string;
  montantAllocation?: number;
  nbrPC?: number;
  nbrImprimante?: number;
  nbrPersonneConnaissanceInfo?: number;
  nbrPersonneOperationelApresFormation?: number;
  coutEstimationAmenagement?: number;
  coutEstimationEquipement?: number;
  observation?: string;
    longitude?: number;
    latitude?: number;
  factures?: CentreFacture[];
};
